package repo;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import domain.RolesPermissions;
import domain.User;
import map.IMaper;
import uow.IUnitOfWork;

public class RolesPermissionsRepository extends RepoBase<RolesPermissions>  implements IRolesPermissions{
	
	public RolesPermissionsRepository(Connection connection, IMaper<RolesPermissions> mapper, IUnitOfWork uow) {
		super(connection,mapper, uow);
	}

	public void setUpdateQuery(RolesPermissions u) throws SQLException {
		update.setInt(1, u.getRoleId());
		update.setInt(2, u.getPermissionId());
		update.setInt(3, u.getId());
	}

	public void setInsertQuery(RolesPermissions u) throws SQLException {
		insert.setInt(1, u.getRoleId());
		insert.setInt(2, u.getPermissionId());
	}


	protected String tableName() {
		return "t_sys_permissions";
	}
	
	protected String createTableSql() {
		return "CREATE TABLE t_sys_permissions("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
			//	+"id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,"
				
				+ "roleId VARCHAR(20)," + "permissionId VARCHAR(20)" + ")";
	}
	
	protected String insertSql() {
		return "INSERT INTO t_sys_permissions(roleId, permissionId) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE t_sys_permissions SET roleId = ?, permissionId = ? WHERE id = ?";
	}

	public List<RolesPermissions> Permissions(RolesPermissions user) {
		// TODO Auto-generated method stub
		return null;
	}

	

}
