package repo;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import domain.UserRoles;
import map.IMaper;
import uow.IUnitOfWork;


public class UserRolesRepository extends   RepoBase<UserRoles> implements IUserRoles{


	public UserRolesRepository(Connection connection, IMaper<UserRoles> mapper, IUnitOfWork uow) {
		super(connection,mapper, uow);
	}
	
	public void setUpdateQuery(UserRoles u) throws SQLException {
		update.setInt(1, u.getUserId());
		update.setInt(2, u.getRoleId());
		update.setInt(3, u.getId());
	}

	public void setInsertQuery(UserRoles u) throws SQLException {
		insert.setInt(1, u.getUserId());
		insert.setInt(2, u.getRoleId());
	}


	protected String tableName() {
		return "t_sys_roles";
	}
	
	protected String createTableSql() {
		return "CREATE TABLE t_sys_roles("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
			//	+"id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,"
				
				+ "UserId VARCHAR(20)," + "RoleId VARCHAR(20)" + ")";
	}
	
	protected String insertSql() {
		return "INSERT INTO t_sys_roles(UserId, RoleId) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE t_sys_roles SET UserId = ?, RoleId = ? WHERE id = ?";
	}

	public List<UserRoles> userId(int userId) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<UserRoles> roleId(int rolesId) {
		// TODO Auto-generated method stub
		return null;
	}

	
	
}
