package repo;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import domain.User;
import map.IMaper;
import uow.IUnitOfWork;


public class UserRepository extends RepoBase<User>  implements IUserRepository{
	
	
	public UserRepository(Connection connection, IMaper<User> mapper, IUnitOfWork uow) {
		super(connection,mapper, uow);
	}

	public void setUpdateQuery(User u) throws SQLException {
		update.setString(1, u.getLogin());
		update.setString(2, u.getPassword());
		update.setInt(3, u.getId());
	}

	public void setInsertQuery(User u) throws SQLException {
		insert.setString(1, u.getLogin());
		insert.setString(2, u.getPassword());
	}


	protected String tableName() {
		return "t_sys_users";
	}
	
	protected String createTableSql() {
		return "CREATE TABLE t_sys_users("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
			//	+"id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,"
				
				+ "login VARCHAR(20)," + "password VARCHAR(20)" + ")";
	}
	
	protected String insertSql() {
		return "INSERT INTO t_sys_users(login, password) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE t_sys_users SET login = ?, password = ? WHERE id = ?";
	}

	
	public List<User> withLogin(String login, String password) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<User> setupPermissions(User user) {
		// TODO Auto-generated method stub
		return null;
	}
		
}
